FROM openjdk:8
COPY target/modulo_evaluaciones-1.0.jar /usr/src/ProyectoEjecutable/modulo-evaluacion.jar
WORKDIR /usr/src/ProyectoEjecutable/
CMD ["java","-jar","/usr/src/ProyectoEjecutable/modulo-evaluacion.jar"]
