FROM openjdk:8
COPY target/ModuloMantenimiento-1.0.0.jar /usr/src/ProyectoEjecutable/modulo-mantenimiento.jar
WORKDIR /usr/src/ProyectoEjecutable/
CMD ["java","-jar","/usr/src/ProyectoEjecutable/modulo-mantenimiento.jar"]
